version: "3"

services:
  db:
    image: postgres:10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres

  makemigrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/app:rw
    networks:
      - postgres
    depends_on:
      - db

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app:rw
    networks:
      - postgres
    depends_on:
      - makemigrations

  toggler:
    build: .
    volumes:
      - .:/app:rw
    ports:
      - 8080:8080
    networks:
      - postgres
    depends_on:
      - migrate

volumes:
  postgres-data:

networks:
  postgres: